#!/bin/bash
# TO TEST - /opt/flir2qr/sh/flir2qr_v09 /opt/flir2qr FireFlight_20180601_121018.7z
# IN CASE OF PERMISSIONS ERRORS, CHECK README at https://github.com/smk762/flir2qr
RED='\033[1;0;31m';
WHITE='\033[1;37m';
BLUE='\033[1;34m';
GREEN='\033[0;32m';
YELLOW='\033[1;33m';
CYAN='\033[0;36m';
PURPLE='\033[1;35m';
RED='\033[1;0;31m';
timestamp=$(date +%F_%T);
IP="$(echo -e $(hostname -I) | tr -d '[:space:]')";
MAPSIZE="2000 1600";
PIXELRANGE="0 8000";

# TODOs
echo 'to do: use pwg files to derive EPSG';
echo 'reduce vector variable to folder';

# Set install and output paths
z7_FILENAME="${2%.*}";
FLIR2QR_PATH="/opt/flir2qr";
WWWPATH="/var/www/html/flir2qr/${z7_FILENAME}";
OUTPATH="${FLIR2QR_PATH}/output/${z7_FILENAME}";

# Define vector layers
ROADSFILE="$FLIR2QR_PATH/vectors/sample_roads_4m_buff.shp";
GRIDFILE="$FLIR2QR_PATH/vectors/100m_grid_wgs84_1m_buff.shp";

# Define legend and logo images (shown on pdf only)
LOGO="$FLIR2QR_PATH/img/logo.gif";
LEGEND="$FLIR2QR_PATH/img/legend.jpg";



# Create output folders for archiving and public transmission
rm -Rf ${WWWPATH};
rm -Rf ${FLIR2QR_PATH}/output/${z7_FILENAME}

mkdir ${WWWPATH};
mkdir ${FLIR2QR_PATH}/output/${z7_FILENAME};
	# create temp subfolders
	declare -a OUTDIRS=('tif' 'qr' 'pdf' 'tif' 'kmz' 'log' 'kml' 'overlay');
	for dir in "${OUTDIRS[@]}"; do  mkdir -p ${FLIR2QR_PATH}/output/${z7_FILENAME}/$dir; done
	for dir in "${OUTDIRS[@]}"; do  mkdir -p ${WWWPATH}/$dir; done

# process data if path/file parameters lead to a file
echo -e "Started processing $2 at $timestamp"$'\r' >> $FLIR2QR_PATH/log/flir2qr.log;
if [ -e ${1}/${2} ]
  then echo -e "${BLUE}Uploaded zipfile $1/$2 detected";
  else echo -e "${RED}$timestamp - $2 does not exist, exiting.${WHITE}"$'\r'; echo -e "$timestamp - $2 does not exist, exiting."$'\r' >> $FLIR2QR_PATH/log/error.log; exit 1; 
fi;

echo -e "Checking for 7z archive";
case "$2" in
*.7z)
	# Create random temp folders for processing
	if [ -e ${FLIR2QR_PATH}/temp.txt ]
		then echo -e "${PURPLE}TempDir has already been spawned";
		else echo -e "$RANDOM" > "$FLIR2QR_PATH/temp.txt";
	fi
	TEMPDIR=$(cat $FLIR2QR_PATH/temp.txt);
	TEMP_PATH=$FLIR2QR_PATH/temp/$TEMPDIR;
	rm -Rf ${TEMP_PATH};
	echo -e "${PURPLE}Creating temporary folders in ${TEMP_PATH}";
	# create temp subfolders
	declare -a PROCDIRS=('raw' 'mga_50' 'wgs84' 'clipfence' 'hotspot' 'basemap' 'roads' 'kmz' 'kml' 'shp' 'grid' 'overlay');
	for dir in "${PROCDIRS[@]}"; do  mkdir -p ${TEMP_PATH}/$dir; done

	# unzip incoming data
	echo -e "Extracting archive";
	7z x $1/$2 -o${TEMP_PATH}
	echo -e "${GREEN}Copying PNGs${YELLOW}";
	cp ${TEMP_PATH}/$z7_FILENAME/HotSpots/*  ${TEMP_PATH}/hotspot
	cp ${TEMP_PATH}/$z7_FILENAME/PNGs/*  ${TEMP_PATH}/raw

	# process all pngs
	for filename in ${TEMP_PATH}/raw/*.png; do
		fname=$(basename "$filename")
		WILDFILE=${fname%.*};
		echo -e "${PURPLE}Processing $fname ${YELLOW}";
		

		# prepare hotspots
		echo -e "${GREEN} Set Hotspot coords to MGA zone 50 ${YELLOW}";
			gdal_translate -a_srs EPSG:28350 ${TEMP_PATH}/hotspot/${WILDFILE}.png ${TEMP_PATH}/mga_50/${WILDFILE}_hs.tif -co COMPRESS=LZW -b 1 -a_nodata 0 -outsize $MAPSIZE -of GTiff;
		echo -e "${GREEN} Coloring HS raster wgs84$ {YELLOW}";
			gdaldem color-relief ${TEMP_PATH}/mga_50/${WILDFILE}_hs.tif ${FLIR2QR_PATH}/color_table.txt ${TEMP_PATH}/mga_50/${WILDFILE}_hs_z50.tif -alpha -exact_color_entry;
		echo -e "${GREEN} Deproject hotspot to wgs84 ${YELLOW}";
			gdalwarp -s_srs EPSG:28350 -t_srs EPSG:4326 ${TEMP_PATH}/mga_50/${WILDFILE}_hs_z50.tif ${TEMP_PATH}/basemap/${WILDFILE}_hs.tif -co COMPRESS=LZW -overwrite -ts 2000 1600 -ts $MAPSIZE -ot Byte;

		# prepare ir imagery
		echo -e "${GREEN}Stamping IR png CRS${YELLOW}";
			gdal_translate -a_srs EPSG:28350 ${TEMP_PATH}/raw/${WILDFILE}.png ${TEMP_PATH}/mga_50/${WILDFILE}_ir_z50.tif -co COMPRESS=LZW -b 1 -b 1 -b 1 -b mask -a_nodata 0 -outsize $MAPSIZE -of GTiff;
			gdal_edit.py -colorinterp_1 red -colorinterp_2 green -colorinterp_3 blue -colorinterp_4 alpha ${TEMP_PATH}/mga_50/${WILDFILE}_ir_z50.tif;
		echo -e "${GREEN}Convert HS raster wgs84${YELLOW}";
			gdalwarp -s_srs EPSG:28350 -t_srs EPSG:4326 ${TEMP_PATH}/mga_50/${WILDFILE}_ir_z50.tif ${TEMP_PATH}/basemap/${WILDFILE}_ir_wgs84.tif -co COMPRESS=LZW -overwrite -ts 2000 1600 -ts $MAPSIZE -ot Byte;
		echo -e "${GREEN}Scaling IR tif ${TEMP_PATH}/basemap/${WILDFILE}_wgs84_scaled.tif ${YELLOW}";
			gdal_translate -a_srs EPSG:4326 ${TEMP_PATH}/basemap/${WILDFILE}_ir_wgs84.tif ${TEMP_PATH}/basemap/${WILDFILE}_ir.tif -scale 0 255 -co COMPRESS=LZW -a_nodata 0 -outsize $MAPSIZE -of GTiff -ot Byte;
		
		# create clip fence
		echo -e "${PURPLE}Creating clip fence${YELLOW}";
			echo -e "${GREEN}Reducing IR raster colours to make clip fence${YELLOW}";
				gdal_merge.py -co NBITS=1 -o ${TEMP_PATH}/clipfence/${WILDFILE}_extent.tif ${TEMP_PATH}/basemap/${WILDFILE}_ir.tif;
			echo -e "${GREEN}Polygonising IR clip fence ${TEMP_PATH}/clipfence/${WILDFILE}_extent.tif ${YELLOW}";
				gdal_polygonize.py ${TEMP_PATH}/clipfence/${WILDFILE}_extent.tif ${TEMP_PATH}/clipfence/${WILDFILE}_extent.shp clip;
		  	echo -e "${GREEN}Dissolving IR clip fence ${TEMP_PATH}/clipfence/${WILDFILE}_fence_wgs84.shp${YELLOW}";
				ogr2ogr ${TEMP_PATH}/clipfence/${WILDFILE}_fence.shp ${TEMP_PATH}/clipfence/${WILDFILE}_extent.shp -dialect sqlite -sql "SELECT ST_Union(geometryProperty) FROM 'clip'";
			echo -e "${GREEN}Stamping IR clip fence ${TEMP_PATH}/clipfence/${WILDFILE}_extent_wgs84.shp ${YELLOW}";
				ogr2ogr ${TEMP_PATH}/clipfence/${WILDFILE}_fence_wgs84.shp ${TEMP_PATH}/clipfence/${WILDFILE}_fence.shp -overwrite -a_srs EPSG:4326;

		# clip vector data
	  	echo -e "${PURPLE}Clipping vectors to IR fence${YELLOW}";
		  	echo -e "${GREEN}Clipping grid ${YELLOW}";
			  	ogr2ogr -clipsrc ${TEMP_PATH}/clipfence/${WILDFILE}_fence_wgs84.shp -clipsrclayer ${WILDFILE}_fence_wgs84 ${TEMP_PATH}/grid/${WILDFILE}_grid.shp $GRIDFILE -a_srs EPSG:4326 -progress; 
			echo -e "${GREEN}Clipping roads ${YELLOW}";
				ogr2ogr -clipsrc ${TEMP_PATH}/clipfence/${WILDFILE}_fence_wgs84.shp -clipsrclayer ${WILDFILE}_fence_wgs84 ${TEMP_PATH}/roads/${WILDFILE}_roads.shp $ROADSFILE -a_srs EPSG:4326 -progress;

		#convert clipped vectors to rasters
		echo -e "${PURPLE}Burning vectors to raster"; 
		  	echo -e "${GREEN}Burning grid ${TEMP_PATH}/grid/${WILDFILE}_grid.tif ${YELLOW} ${YELLOW}";
				gdal_rasterize -burn 10 -burn 250 -burn 250 -burn 255 -ts $MAPSIZE ${TEMP_PATH}/grid/${WILDFILE}_grid.shp ${TEMP_PATH}/basemap/${WILDFILE}_grid.tif -co COMPRESS=LZW -init 0 -a_srs EPSG:4326 -ot Byte;
				gdal_edit.py -colorinterp_4 alpha ${TEMP_PATH}/basemap/${WILDFILE}_grid.tif;
	  		echo -e "${GREEN}Burning roads ${TEMP_PATH}/roads/${WILDFILE}_roads.tif${YELLOW}";
				gdal_rasterize -burn 39 -burn 50 -burn 216 -burn 255 -ts $MAPSIZE ${TEMP_PATH}/roads/${WILDFILE}_roads.shp ${TEMP_PATH}/basemap/${WILDFILE}_roads.tif -co COMPRESS=LZW -init 0 -a_srs EPSG:4326 -ot Byte;
				gdal_edit.py -colorinterp_1 red -colorinterp_2 green -colorinterp_3 blue -colorinterp_4 alpha ${TEMP_PATH}/basemap/${WILDFILE}_roads.tif;								
			echo -e "${PURPLE}Merging rasters into final map ${OUTPATH}/${WILDFILE}.tif ${YELLOW}";			
				gdal_merge.py -o ${OUTPATH}/tif/${WILDFILE}_merged.tif ${TEMP_PATH}/basemap/${WILDFILE}_ir.tif ${TEMP_PATH}/basemap/${WILDFILE}_roads.tif ${TEMP_PATH}/basemap/${WILDFILE}_hs.tif ${TEMP_PATH}/basemap/${WILDFILE}_grid.tif;

			# Moving output into www folders
			echo -e "${PURPLE}Adding ${OUTPATH}/tif/${WILDFILE}_merged.tif to ${WWWPATH}/ ${YELLOW}"; 
			cp -f ${OUTPATH}/tif/${WILDFILE}_merged.tif ${WWWPATH}/tif/${WILDFILE}_merged.tif;
			echo -e "${PURPLE}Creating GeoPDF${YELLOW}"; 
		  	gdal_translate ${OUTPATH}/tif/${WILDFILE}_merged.tif ${OUTPATH}/pdf/${WILDFILE}_merged.pdf -of PDF -a_srs EPSG:4326 -co EXTRA_IMAGES=$LOGO,5,0,1,$LEGEND,5,85,1 -outsize $MAPSIZE;
			cp -f ${OUTPATH}/pdf/${WILDFILE}_merged.pdf ${WWWPATH}/pdf/${WILDFILE}_merged.pdf;
		  	echo -e "${PURPLE}Creating KML${YELLOW}";
		  	gdal2tiles.py -k -t $2 ${OUTPATH}/tif/${WILDFILE}_merged.tif ${TEMP_PATH}/kmz/${WILDFILE}_merged.kml;
		  	cd ${TEMP_PATH}/kmz/${WILDFILE}_merged.kml;
		  	zip ${OUTPATH}/overlay/${WILDFILE}_overlay.zip . -r;
			mv -f ${OUTPATH}/overlay/${WILDFILE}_overlay.zip ${WWWPATH}/kmz/${WILDFILE}_overlay.kmz;

			echo -e "${PURPLE}generating QR code for http://$IP/flir2qr/${WILDFILE}.tif ${YELLOW}";
			qrencode -o ${OUTPATH}/qr/${WILDFILE}_merged_tif.png http://$IP/flir2qr/${z7_FILENAME}/tif/${WILDFILE}_merged.tif;
		  	qrencode -o ${OUTPATH}/qr/${WILDFILE}_merged_pdf.png http://$IP/flir2qr/${z7_FILENAME}/pdf/${WILDFILE}_merged.pdf;

		  	cp -f ${OUTPATH}/qr/* ${WWWPATH}/qr;
		  	cp -f $FLIR2QR_PATH/kml/template.kml ${OUTPATH}/kml/${WILDFILE}_qr.kml;

		  	centroid=$(echo $(gdalinfo ${TEMP_PATH}/clipfence/${WILDFILE}_extent.tif | grep Center |  grep -o '(.*).' | sed 's/[()]//g'));
		  	echo -e "${PURPLE}Creating $WILDFILE centroid placemark at $centroid ${YELLOW}";

		  	sed -i 's/WILDFILE/'"$WILDFILE"'_merged_pdf.png/g' "${OUTPATH}"'/kml/'"${WILDFILE}"'_qr.kml';
		  	sed -i 's/CENTROID/'"$centroid"'/g' "${OUTPATH}"'/kml/'"${WILDFILE}"'_qr.kml';
		  	cd  ${OUTPATH}
		  	zip ${WILDFILE}_qr.zip ${OUTPATH}/kml/${WILDFILE}_qr.kml ${WWWPATH}/qr/${WILDFILE}_merged_pdf.png -j;
			mv -f ${WILDFILE}_qr.zip ${WWWPATH}/kmz/${WILDFILE}_qr.kmz;
		  	echo -e "${BLUE}moving files $2 complete! ${WHITE}";
		done
		echo -e "Processing $2 complete"'\r' >> $FLIR2QR_PATH/log/flir2qr.log;
		echo -e "${BLUE}Processing $2 complete! ${WHITE}";
		echo -e "${GREEN}Output data available at http://${IP}/flir2qr/${z7_FILENAME} ${WHITE}";

		rm -Rf /opt/flir2qr/temp/*;
		rm -Rf /opt/flir2qr/temp/*;
		rm -Rf ${WWWPATH}/kml;
		rm -Rf ${WWWPATH}/overlay;
		cp -f $FLIR2QR_PATH/log/* ${WWWPATH}/log;
	 ;;
	*)
	  echo -e "${RED}Unexpected file type '$2'. 7z Archive Only! ${WHITE}";
	  echo "$timestamp - bad filetype uploaded - $2"$'\r' >> ${FLIR2QR_PATH}/log/error.log;
	;;
esac
		
